// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: passport.proto

package passport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Passport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//repeated Device DeviceInformation = 1;
	Header              []*Passport_Header `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty"`
	SessionID           string             `protobuf:"bytes,3,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	AuthenticatedUserID string             `protobuf:"bytes,4,opt,name=AuthenticatedUserID,proto3" json:"AuthenticatedUserID,omitempty"`
	AuthorisedUserID    string             `protobuf:"bytes,5,opt,name=AuthorisedUserID,proto3" json:"AuthorisedUserID,omitempty"`
	// int64 need to replace with TimeSpan
	//google.protobuf.Duration VirtualNowOffset = 6;
	LocaleChain  string `protobuf:"bytes,6,opt,name=LocaleChain,proto3" json:"LocaleChain,omitempty"`
	CustomerCode string `protobuf:"bytes,7,opt,name=CustomerCode,proto3" json:"CustomerCode,omitempty"`
}

func (x *Passport) Reset() {
	*x = Passport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Passport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passport) ProtoMessage() {}

func (x *Passport) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passport.ProtoReflect.Descriptor instead.
func (*Passport) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{0}
}

func (x *Passport) GetHeader() []*Passport_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Passport) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *Passport) GetAuthenticatedUserID() string {
	if x != nil {
		return x.AuthenticatedUserID
	}
	return ""
}

func (x *Passport) GetAuthorisedUserID() string {
	if x != nil {
		return x.AuthorisedUserID
	}
	return ""
}

func (x *Passport) GetLocaleChain() string {
	if x != nil {
		return x.LocaleChain
	}
	return ""
}

func (x *Passport) GetCustomerCode() string {
	if x != nil {
		return x.CustomerCode
	}
	return ""
}

type Passport_Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PassportProvider string `protobuf:"bytes,1,opt,name=PassportProvider,proto3" json:"PassportProvider,omitempty"`
}

func (x *Passport_Header) Reset() {
	*x = Passport_Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passport_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Passport_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passport_Header) ProtoMessage() {}

func (x *Passport_Header) ProtoReflect() protoreflect.Message {
	mi := &file_passport_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passport_Header.ProtoReflect.Descriptor instead.
func (*Passport_Header) Descriptor() ([]byte, []int) {
	return file_passport_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Passport_Header) GetPassportProvider() string {
	if x != nil {
		return x.PassportProvider
	}
	return ""
}

var File_passport_proto protoreflect.FileDescriptor

var file_passport_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x22, 0xb5, 0x02, 0x0a, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x30, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x10, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x73, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x73, 0x65, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x65,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x34, 0x0a, 0x06,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x50, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x61, 0x73, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_passport_proto_rawDescOnce sync.Once
	file_passport_proto_rawDescData = file_passport_proto_rawDesc
)

func file_passport_proto_rawDescGZIP() []byte {
	file_passport_proto_rawDescOnce.Do(func() {
		file_passport_proto_rawDescData = protoimpl.X.CompressGZIP(file_passport_proto_rawDescData)
	})
	return file_passport_proto_rawDescData
}

var file_passport_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_passport_proto_goTypes = []interface{}{
	(*Passport)(nil),        // 0: passport.Passport
	(*Passport_Header)(nil), // 1: passport.Passport.Header
}
var file_passport_proto_depIdxs = []int32{
	1, // 0: passport.Passport.header:type_name -> passport.Passport.Header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_passport_proto_init() }
func file_passport_proto_init() {
	if File_passport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_passport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Passport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passport_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Passport_Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_passport_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_passport_proto_goTypes,
		DependencyIndexes: file_passport_proto_depIdxs,
		MessageInfos:      file_passport_proto_msgTypes,
	}.Build()
	File_passport_proto = out.File
	file_passport_proto_rawDesc = nil
	file_passport_proto_goTypes = nil
	file_passport_proto_depIdxs = nil
}
